---
title: 'PCA and Factor Analysis: Star Wars Dataset'
author: "Paul Harmon"
date: "April 10, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

##The Data

```{r}

jedi <- read.csv("sw.csv", header = TRUE)
head(jedi)
names(jedi)
```


##Let's Just Look at Character Ratings
Characters are rated on a likert scale, from 1 (very unfavorable) to 5 (very favorable).
*Note that we don't have a good definition for what 'favorable' really means. 

```{r}

jdat <- na.omit(jedi[,c(18:29)])
as.numeric.factor <- function(x) {as.numeric(levels(x))[x]}
factor_coerce <- function(x) {as.numeric.factor(factor(x))}
apply(jdat,2,factor_coerce)

```

Well we want to know which characters (questions) drive the most variability. Let's look at a quick PCA: 
```{r}

##Principal Components Analysis
pc1 <- prcomp(jdat)
plot(pc1$x[,1], pc1$x[,2], type = "n", main = "Principal Components")
text(pc1$x[,1], pc1$x[,2], labels = colnames(jdat))

biplot(pc1, var.axes = TRUE, col = c('gray80','red3'), xlim = c(-.18,.15))

summary(pc1) #suggests we'd need several factors



```


##Factor Analysis:

```{r}
##
factanal(jdat, 4) #keep going, need 5
factanal(jdat,5)



```

